CREATE DATABASE `medicines` CAHARACTER SET utf8;

CREATE TABLE `makers` (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	created_at TIMESTAMP DEFAULT NOW(),
	country VARCHAR(255)
);

CREATE TABLE `medicine` (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	is_recipe BOOLEAN NOT NULL DEFAULT 0,
	route TEXT 
);

CREATE TABLE `pharmacies` (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	address VARCHAR(255) NOT NULL,
	start_at TIMESTAMP NOT NULL,
	end_at TIMESTAMP NOT NULL
);
